CREATE TYPE "public"."alert_job_status" AS ENUM('pending', 'sent', 'failed');--> statement-breakpoint
CREATE TABLE "alert_job" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"student_alert_id" bigint NOT NULL,
	"accommodation_id" bigint NOT NULL,
	"status" "alert_job_status" DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"sent_at" timestamp with time zone,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "alert_job_unique" UNIQUE("user_id","student_alert_id","accommodation_id")
);
--> statement-breakpoint
ALTER TABLE "alert_job" ADD CONSTRAINT "alert_job_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alert_job" ADD CONSTRAINT "alert_job_student_alert_id_student_alert_id_fk" FOREIGN KEY ("student_alert_id") REFERENCES "public"."student_alert"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alert_job" ADD CONSTRAINT "alert_job_accommodation_id_accommodation_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation_accommodation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "alert_job_user_id_idx" ON "alert_job" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "alert_job_status_idx" ON "alert_job" USING btree ("status");