-- ⚠️  Migration assemblée manuellement (renames Django + backfill typologies) — NE PAS régénérer.
-- Rejoue en séquence : renommage des tables, création accommodation_typology + backfill depuis
-- les colonnes plates, puis suppression de ces colonnes. Le SET CONSTRAINTS ALL IMMEDIATE (0039)
-- vide les triggers FK déférés en attente avant les DROP (sinon erreur 55006).

--> statement-breakpoint
-- Lot 1 + 2 : rename Django app_model tables to clean singular snake_case names
ALTER TABLE "accommodation_accommodation" RENAME TO "accommodation";
--> statement-breakpoint
ALTER TABLE "account_owner" RENAME TO "owner";
--> statement-breakpoint
ALTER TABLE "accommodation_externalsource" RENAME TO "external_source";
--> statement-breakpoint
ALTER TABLE "accommodation_favoriteaccommodation" RENAME TO "favorite_accommodation";
--> statement-breakpoint
ALTER TABLE "accommodation_importblocklist" RENAME TO "import_blocklist";
--> statement-breakpoint
ALTER TABLE "territories_city" RENAME TO "city";
--> statement-breakpoint
ALTER TABLE "territories_department" RENAME TO "department";
--> statement-breakpoint
ALTER TABLE "territories_academy" RENAME TO "academy";
--> statement-breakpoint
ALTER TABLE "faq_question_answer" RENAME TO "faq_question";
--> statement-breakpoint
ALTER TABLE "import_jobs" RENAME TO "import_job";
--> statement-breakpoint
ALTER TABLE "event_stats" RENAME TO "event_stat";
--> statement-breakpoint
-- Lot 4a : enforce referential integrity on favorite_accommodation.user_id
DELETE FROM "favorite_accommodation" WHERE NOT EXISTS (SELECT 1 FROM "user" u WHERE u.id = "favorite_accommodation"."user_id");
--> statement-breakpoint
ALTER TABLE "favorite_accommodation" ALTER COLUMN "user_id" SET DATA TYPE text;
--> statement-breakpoint
ALTER TABLE "favorite_accommodation" ADD CONSTRAINT "favorite_accommodation_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

--> statement-breakpoint
CREATE TYPE "public"."accommodation_typology_type" AS ENUM('t1', 't1_bis', 't2', 't3', 't4', 't5', 't6', 't7_more');--> statement-breakpoint
CREATE TABLE "accommodation_typology" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_typology_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"accommodation_id" bigint NOT NULL,
	"type" "accommodation_typology_type" NOT NULL,
	"price_min" integer,
	"price_max" integer,
	"superficie_min" integer,
	"superficie_max" integer,
	"nb_total" integer,
	"nb_available" integer,
	"colocation" boolean DEFAULT false NOT NULL,
	CONSTRAINT "accommodation_typology_accommodation_id_type_unique" UNIQUE("accommodation_id","type")
);
--> statement-breakpoint
ALTER TABLE "accommodation" ADD COLUMN "nb_available_apartments" integer;--> statement-breakpoint
ALTER TABLE "accommodation" ADD COLUMN "price_max" integer;--> statement-breakpoint
ALTER TABLE "accommodation_typology" ADD CONSTRAINT "accommodation_typology_accommodation_id_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "accommodation_typology_accommodation_id_idx" ON "accommodation_typology" USING btree ("accommodation_id");--> statement-breakpoint
-- Backfill accommodation_typology from the flat columns. One INSERT per typology, emitting a
-- row only when that typology has at least one non-null field. `colocation` is backfilled by the
-- isPerPersonTypology rule (false for T1/T1 bis/T2, true for T3..T7+) — heuristic, never persisted before.
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t1',"price_min_t1","price_max_t1","superficie_min_t1","superficie_max_t1","nb_t1","nb_t1_available",false FROM "accommodation"
WHERE "nb_t1" IS NOT NULL OR "nb_t1_available" IS NOT NULL OR "price_min_t1" IS NOT NULL OR "price_max_t1" IS NOT NULL OR "superficie_min_t1" IS NOT NULL OR "superficie_max_t1" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t1_bis',"price_min_t1_bis","price_max_t1_bis","superficie_min_t1_bis","superficie_max_t1_bis","nb_t1_bis","nb_t1_bis_available",false FROM "accommodation"
WHERE "nb_t1_bis" IS NOT NULL OR "nb_t1_bis_available" IS NOT NULL OR "price_min_t1_bis" IS NOT NULL OR "price_max_t1_bis" IS NOT NULL OR "superficie_min_t1_bis" IS NOT NULL OR "superficie_max_t1_bis" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t2',"price_min_t2","price_max_t2","superficie_min_t2","superficie_max_t2","nb_t2","nb_t2_available",false FROM "accommodation"
WHERE "nb_t2" IS NOT NULL OR "nb_t2_available" IS NOT NULL OR "price_min_t2" IS NOT NULL OR "price_max_t2" IS NOT NULL OR "superficie_min_t2" IS NOT NULL OR "superficie_max_t2" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t3',"price_min_t3","price_max_t3","superficie_min_t3","superficie_max_t3","nb_t3","nb_t3_available",true FROM "accommodation"
WHERE "nb_t3" IS NOT NULL OR "nb_t3_available" IS NOT NULL OR "price_min_t3" IS NOT NULL OR "price_max_t3" IS NOT NULL OR "superficie_min_t3" IS NOT NULL OR "superficie_max_t3" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t4',"price_min_t4","price_max_t4","superficie_min_t4","superficie_max_t4","nb_t4","nb_t4_available",true FROM "accommodation"
WHERE "nb_t4" IS NOT NULL OR "nb_t4_available" IS NOT NULL OR "price_min_t4" IS NOT NULL OR "price_max_t4" IS NOT NULL OR "superficie_min_t4" IS NOT NULL OR "superficie_max_t4" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t5',"price_min_t5","price_max_t5","superficie_min_t5","superficie_max_t5","nb_t5","nb_t5_available",true FROM "accommodation"
WHERE "nb_t5" IS NOT NULL OR "nb_t5_available" IS NOT NULL OR "price_min_t5" IS NOT NULL OR "price_max_t5" IS NOT NULL OR "superficie_min_t5" IS NOT NULL OR "superficie_max_t5" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t6',"price_min_t6","price_max_t6","superficie_min_t6","superficie_max_t6","nb_t6","nb_t6_available",true FROM "accommodation"
WHERE "nb_t6" IS NOT NULL OR "nb_t6_available" IS NOT NULL OR "price_min_t6" IS NOT NULL OR "price_max_t6" IS NOT NULL OR "superficie_min_t6" IS NOT NULL OR "superficie_max_t6" IS NOT NULL;--> statement-breakpoint
INSERT INTO "accommodation_typology" ("accommodation_id","type","price_min","price_max","superficie_min","superficie_max","nb_total","nb_available","colocation")
SELECT "id",'t7_more',"price_min_t7_more","price_max_t7_more","superficie_min_t7_more","superficie_max_t7_more","nb_t7_more","nb_t7_more_available",true FROM "accommodation"
WHERE "nb_t7_more" IS NOT NULL OR "nb_t7_more_available" IS NOT NULL OR "price_min_t7_more" IS NOT NULL OR "price_max_t7_more" IS NOT NULL OR "superficie_min_t7_more" IS NOT NULL OR "superficie_max_t7_more" IS NOT NULL;--> statement-breakpoint
-- Backfill ALL four parent aggregates from the freshly inserted typology rows, with the exact same
-- semantics as typologyAggregates() (src/server/lib/typologies.ts) so a legacy row is never left with
-- a mix of recomputed (price_max/nb_available) and stale-Django (price_min/nb_total) values — which
-- would drift silently at the next write and skew alert matching / price filter (priceMin) and the
-- displayed "N logements" total (nbTotalApartments).
-- nb_available_apartments stays NULL when every child nb_available is NULL (preserves "unknown availability").
UPDATE "accommodation" a SET
  "price_min" = sub.price_min,
  "price_max" = sub.price_max,
  "nb_total_apartments" = sub.nb_total,
  "nb_available_apartments" = sub.nb_available
FROM (
  SELECT "accommodation_id",
    MIN(NULLIF("price_min", 0)) AS price_min,
    MAX(NULLIF("price_max", 0)) AS price_max,
    SUM("nb_total") AS nb_total,
    CASE WHEN bool_or("nb_available" IS NOT NULL) THEN SUM("nb_available") ELSE NULL END AS nb_available
  FROM "accommodation_typology"
  GROUP BY "accommodation_id"
) sub
WHERE a."id" = sub."accommodation_id";
--> statement-breakpoint
-- The 0038 backfill UPDATE on "accommodation" queues DEFERRED FK check events (owner_id FK is
-- DEFERRABLE INITIALLY DEFERRED). Since the whole migration batch runs in one transaction, those
-- pending trigger events block the ALTER TABLE below (error 55006). Flush them first.
SET CONSTRAINTS ALL IMMEDIATE;--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t1";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t1_bis";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t2";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t3";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t4";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t5";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t6";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t7_more";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t1_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t1_bis_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t2_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t3_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t4_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t5_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t6_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "nb_t7_more_available";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t1";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t1";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t1_bis";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t1_bis";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t2";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t2";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t3";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t3";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t4";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t4";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t5";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t5";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t6";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t6";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_min_t7_more";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "price_max_t7_more";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t1";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t1";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t1_bis";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t1_bis";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t2";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t2";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t3";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t3";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t4";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t4";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t5";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t5";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t6";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t6";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_min_t7_more";--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "superficie_max_t7_more";
--> statement-breakpoint
ALTER TABLE "accommodation" DROP COLUMN "images_count";
